### ISSUE TITLE
howto view the logs?

### ISSUE THREAD

**Issue by jjoe64** [EngsShi/react-native-xlog#24]
I integrated it and it produced me 2 files:
* myapp.mmap2
* myapp_20170723.xlog

Both files are binary and cannot be viewed my any text editor.
So how can I access and view these log files?

**Comment by EngsShi** [comment]
You can use this [script](https://github.com/Tencent/mars/blob/master/mars/log/crypt/decode_mars_nocrypt_log_file.py) to decode log file.
But we use mars framewok is old version, not sure if it's compatible.

**Comment by jjoe64** [comment]
it's working! would be nice if you add this to the README! Good job btw
