### ISSUE TITLE
XLogBridge.installUncaughtCrashHandler is not a function

### ISSUE THREAD

**Issue by gofugui** [EngsShi/react-native-xlog#27]
//开启日志管理模块

```
>    XLog.open();

>    XLog.installUncaughtCrashHandler();
```

初始化上述模块的时候，出现警告信息：

> TypeError: XLogBridge.installUncaughtCrashHandler is not a function
> TypeError: XLogBridge.installUncaughtCrashHandler is not a function

并且在XLogModule.java中也没有看到installUncaughtCrashHandler 方法

**Comment by EngsShi** [comment]
fix
