### ISSUE TITLE
Getting ios simulator build errors after adding react-native-xlog to the project

### ISSUE THREAD

**Issue by dodikk** [EngsShi/react-native-xlog#29]
```
/node_modules/react-native-xlog/ios/XLogForRN/Util/LogHelper.h:23:9: 'mars/xlog/xloggerbase.h' file not found

#import <mars/xlog/xloggerbase.h>
                                                                                            ^


▸ Compiling XLogCrashHandler.mm
** BUILD FAILED **
```

**Comment by dodikk** [comment]
```
react-native run-ios --simulator="iPhone 7"
```
A shell command I've used.

**Comment by EngsShi** [comment]
you need [build xlog](https://github.com/Tencent/mars/#apple), and add to you project

**Comment by dodikk** [comment]
> you need build xlog, and add to you project

@EngsShi , thanks for explaining the failure reason.

If the readme has this info, please consider improving its visibility. Maybe, by highlighting it 
```
LIKE THIS
```

**Comment by dodikk** [comment]
@EngsShi , could you please explain the reasons for not including the native part to the NPM package? Is it due to a lack of time? Are there any licensing, legal or technical reasons preventing from doing so?
