### ISSUE TITLE
XLogPackage.java:23: 错误: 方法不会覆盖或实现超类型的方法   @Override

### ISSUE THREAD

**Issue by Mar-er** [EngsShi/react-native-xlog#30]
"react": "^16.4.2",
    "react-native": "0.55.4",

![image](https://user-images.githubusercontent.com/19943499/47345558-9d4d3780-d6dd-11e8-94d3-b11f859cc30c.png)

**Comment by EngsShi** [comment]
RN0.47.0版本删除了这个继承关系，已去除 @Override 注释。  [0.6.1版本已发布](https://www.npmjs.com/package/react-native-xlog)
