### ISSUE TITLE
请问还能再提问吗？Runtime is not ready for debugging. Make sure Packager server is running

### ISSUE THREAD

**Issue by YiFan-Tong** [EngsShi/react-native-xlog#32]
平台：iOS  
RN： 0.57.8
react: 16.8.3
mars:用的最新的，重新打了个framework
有个场景，产生了大量的日志数据：首先，启动项目，command+D,选择debugger模式，然后点击示例中的crash，（可以根据xcode控制台那边的路径找到日志文件）产生日志文件，之后，将服务关闭，此时可以看到日志文件一直在增大，解压之后，发现都是
[F][2019-05-10 +8.0 20:17:35.356][0, 105553120254336][log][FMXXlog.mm, setRCTLog, 131][2019-05-10 20:17:35.357 [fatal][tid:com.facebook.react.WebSocketExecutor] Runtime is not ready for debugging. Make sure Packager server is running.

这样的报错，每毫秒都产生一条，几十秒之内，日志文件都快破10M了

想请问一下又什么方法可以debugger模式下，不捕获的异常

**Comment by EngsShi** [comment]
https://github.com/Tencent/mars/#xlog-init-3

**Comment by EngsShi** [comment]
https://github.com/Tencent/mars/#xlog-init-4

**Comment by EngsShi** [comment]
如需关闭，请参考mars的xlog配置

**Comment by EngsShi** [comment]
或者使用 uninstallUncaughtCrashHandler 方法，停止crash的捕获

**Comment by YiFan-Tong** [comment]
好的，谢谢你，我明天尝试一下

**Comment by YiFan-Tong** [comment]
> 或者使用 uninstallUncaughtCrashHandler 方法，停止crash的捕获
你好，我试了一下，那个异常是mars本身捕获到的，使用 uninstallUncaughtCrashHandler 方法，没有办法停止，Runtime is not ready for debugging. Make sure Packager server is running.可能并不是crash，只是一个异常，Mars文档一直宣称不会捕获crash，所以我觉得可能是Mars那边的原因

**Comment by EngsShi** [comment]
确认了下，这个错误并非崩溃日志，是正常的开发异常log。
xlog只是正常捕获日志并且打印，和crash无关。尝试修改log的等级为info，或者更高来避免写入这部分内容。

**Comment by YiFan-Tong** [comment]
> 尝试修改log的等级为info
好的，谢谢你

**Comment by YiFan-Tong** [comment]
> > 尝试修改log的等级为info
> > 好的，谢谢你
x

> > 尝试修改log的等级为info
> > 好的，谢谢你

你好，谢谢你，我改了两个地方，现在可以了，

在这边禁了[self setRCTLog];方法，并在setFatalHandle做了判断
-(instancetype)init
{
    self = [super init];
    if (self) {
        [self setFatalHandle];
//        [self setRCTLog];
    }
    return self;
}

-(void)setFatalHandle {
    RCTSetFatalHandler(^(NSError *error) {
        NSString *errorMsg = [error description];
        NSString *targetStr = @"Make sure Packager server is running";
        
        if ([errorMsg containsString:targetStr]) {
            return;
        } else {
            LOG_MESSAGE(kLevelFatal, "ios fatal handle", errorMsg);
        }
    });
}

这样做，目前能满足我的需求
